### ISSUE TITLE
If messages fail to be saved to MongoDB, they will be rejected (but NOT requeued).

### ISSUE THREAD

**Issue by anthonymartin** [typeduck/amqp-to-mongo#1]
Is there a way to re-queue the messages if Mongo is down or if the message can't be saved? This would be a very useful configuration parameter.

**Comment by typeduck** [comment]
I will look into this, apparently it can be specified at the time the message is rejected. Feel free to send a pull request if you are faster.

**Comment by typeduck** [comment]
This is fixed in https://github.com/typeduck/amqp-to-mongo/commit/da457a493f41a7af3b391b4ec74492df8fa75335
